<h1>Login</h1>

<?php if (!empty($this->error)): ?>
    <div style="padding:10px; border:1px solid #f00; margin-bottom:10px;">
        <?= $this->escapeHtml($this->error) ?>
    </div>
<?php endif; ?>

<form method="post" action="<?= $this->url('login') ?>">
    <input type="hidden" name="csrf" value="<?= $this->escapeHtmlAttr($this->csrfToken('login_form')) ?>">
    <div style="margin-bottom:10px;">
        <label>Email</label><br>
        <input type="email" name="email" required autocomplete="email">
    </div>

    <div style="margin-bottom:10px">
        <label>Senha</label><br>
        <input type="password" name="password" required autocomplete="current-password">
    </div>

    <button type="submit">Entrar</button>
</form>